
import { VendorProductWithVendor } from "../types/vendor.types";

// Mock vendor products
export const mockVendorProducts: VendorProductWithVendor[] = [
  {
    id: "p1",
    sku: "AC-E-001",
    name: "Premium Wireless Headphones",
    category: "Electronics",
    vendorName: "Acme Supplies",
    price: 129.99,
    cost: 78.50,
    stockQuantity: 45,
    stockStatus: "In Stock",
    qualityScore: 95,
    qualityIssues: 0,
  },
  {
    id: "p2",
    sku: "AC-E-002",
    name: "Bluetooth Speaker",
    category: "Electronics",
    vendorName: "Acme Supplies",
    price: 79.99,
    cost: 42.00,
    stockQuantity: 32,
    stockStatus: "In Stock",
    qualityScore: 94,
    qualityIssues: 0,
  },
  {
    id: "p3",
    sku: "GD-C-001",
    name: "Men's Casual Shirt",
    category: "Clothing",
    vendorName: "Global Distributors",
    price: 49.99,
    cost: 22.50,
    stockQuantity: 12,
    stockStatus: "Low Stock",
    qualityScore: 91,
    qualityIssues: 0,
  },
  {
    id: "p4",
    sku: "GD-H-001",
    name: "Decorative Throw Pillow",
    category: "Home Goods",
    vendorName: "Global Distributors",
    price: 29.99,
    cost: 12.25,
    stockQuantity: 45,
    stockStatus: "In Stock",
    qualityScore: 90,
    qualityIssues: 0,
  },
  {
    id: "p5",
    sku: "MM-E-001",
    name: "Smart Thermostat",
    category: "Electronics",
    vendorName: "Metro Manufacturing",
    price: 149.99,
    cost: 85.75,
    stockQuantity: 0,
    stockStatus: "Out of Stock",
    qualityScore: 88,
    qualityIssues: 2,
  },
  {
    id: "p6",
    sku: "ST-C-001",
    name: "Women's Sundress",
    category: "Clothing",
    vendorName: "Sunshine Textiles",
    price: 59.99,
    cost: 28.50,
    stockQuantity: 30,
    stockStatus: "In Stock",
    qualityScore: 93,
    qualityIssues: 0,
  },
  {
    id: "p7",
    sku: "EPS-P-001",
    name: "Biodegradable Packaging Set",
    category: "Packaging",
    vendorName: "EcoPackage Solutions",
    price: 19.99,
    cost: 9.75,
    stockQuantity: 65,
    stockStatus: "In Stock",
    qualityScore: 90,
    qualityIssues: 0,
  },
];
