
import { VendorDetail } from "../types/vendor.types";

// Mock vendor detail
export const mockVendorDetail: VendorDetail = {
  id: "v1",
  name: "Acme Supplies",
  status: "active",
  isPreferred: true,
  rating: 4.8,
  categories: ["Electronics", "Accessories", "Hardware"],
  productsCount: 42,
  totalSpend: 120500,
  lastOrderDate: "2023-06-15",
  onboardedDate: "2021-03-10",
  paymentTerms: "Net 30",
  contact: {
    name: "John Smith",
    email: "john@acmesupplies.com",
    phone: "555-123-4567",
  },
  metrics: {
    onTimeDelivery: 96,
    onTimeDeliveryTrend: 2.3,
    qualityScore: 92,
    qualityScoreTrend: 1.8,
    responseTime: 4.2,
    responseTimeTrend: -8.3,
    issueRate: 1.3,
    issueRateTrend: -0.5,
    historicalData: [
      {
        month: "Jan",
        qualityScore: 88,
        onTimeDelivery: 92,
        issueRate: 2.1,
      },
      {
        month: "Feb",
        qualityScore: 90,
        onTimeDelivery: 94,
        issueRate: 1.8,
      },
      {
        month: "Mar",
        qualityScore: 89,
        onTimeDelivery: 91,
        issueRate: 2.0,
      },
      {
        month: "Apr",
        qualityScore: 91,
        onTimeDelivery: 95,
        issueRate: 1.5,
      },
      {
        month: "May",
        qualityScore: 90,
        onTimeDelivery: 93,
        issueRate: 1.7,
      },
      {
        month: "Jun",
        qualityScore: 92,
        onTimeDelivery: 96,
        issueRate: 1.3,
      },
    ],
  },
  products: [
    {
      id: "p1",
      sku: "AC-E-001",
      name: "Premium Wireless Headphones",
      category: "Electronics",
      price: 129.99,
      cost: 78.50,
      stockQuantity: 45,
      stockStatus: "In Stock",
      qualityScore: 95,
      qualityIssues: 0,
    },
    {
      id: "p2",
      sku: "AC-E-002",
      name: "Bluetooth Speaker",
      category: "Electronics",
      price: 79.99,
      cost: 42.00,
      stockQuantity: 32,
      stockStatus: "In Stock",
      qualityScore: 94,
      qualityIssues: 0,
    },
    {
      id: "p3",
      sku: "AC-A-001",
      name: "Smartphone Case",
      category: "Accessories",
      price: 24.99,
      cost: 8.75,
      stockQuantity: 5,
      stockStatus: "Low Stock",
      qualityScore: 88,
      qualityIssues: 1,
    },
    {
      id: "p4",
      sku: "AC-A-002",
      name: "HDMI Cable",
      category: "Accessories",
      price: 14.99,
      cost: 3.25,
      stockQuantity: 0,
      stockStatus: "Out of Stock",
      qualityScore: 90,
      qualityIssues: 0,
    },
    {
      id: "p5",
      sku: "AC-H-001",
      name: "Screwdriver Set",
      category: "Hardware",
      price: 39.99,
      cost: 18.60,
      stockQuantity: 12,
      stockStatus: "In Stock",
      qualityScore: 92,
      qualityIssues: 0,
    },
  ],
};
